
package br.edu.ifrn.sc.info.pds.negocio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * Eclipse Metro/2.4.8 (RELEASE-2.4.8-e044505; 2022-01-04T13:29:23+0000) JAXWS-RI/2.3.5 JAXWS-API/2.3.3 JAXB-RI/2.3.5 JAXB-API/2.3.3
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FilmeWS", targetNamespace = "http://negocio.pds.info.sc.ifrn.edu.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FilmeWS {


    /**
     * 
     * @param novoFilme
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "inserirFilme", targetNamespace = "http://negocio.pds.info.sc.ifrn.edu.br/", className = "br.edu.ifrn.sc.info.pds.negocio.InserirFilme")
    @ResponseWrapper(localName = "inserirFilmeResponse", targetNamespace = "http://negocio.pds.info.sc.ifrn.edu.br/", className = "br.edu.ifrn.sc.info.pds.negocio.InserirFilmeResponse")
    @Action(input = "http://negocio.pds.info.sc.ifrn.edu.br/FilmeWS/inserirFilmeRequest", output = "http://negocio.pds.info.sc.ifrn.edu.br/FilmeWS/inserirFilmeResponse")
    public boolean inserirFilme(
        @WebParam(name = "novoFilme", targetNamespace = "")
        Filme novoFilme);

    /**
     * 
     * @return
     *     returns java.util.List<br.edu.ifrn.sc.info.pds.negocio.Filme>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarFilmes", targetNamespace = "http://negocio.pds.info.sc.ifrn.edu.br/", className = "br.edu.ifrn.sc.info.pds.negocio.ListarFilmes")
    @ResponseWrapper(localName = "listarFilmesResponse", targetNamespace = "http://negocio.pds.info.sc.ifrn.edu.br/", className = "br.edu.ifrn.sc.info.pds.negocio.ListarFilmesResponse")
    @Action(input = "http://negocio.pds.info.sc.ifrn.edu.br/FilmeWS/listarFilmesRequest", output = "http://negocio.pds.info.sc.ifrn.edu.br/FilmeWS/listarFilmesResponse")
    public List<Filme> listarFilmes();

}
